### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by fgrehm** [sam/harbor#27]
We should definitely have a build set up (maybe [travis-ci](http://travis-ci.org/)) as soon as we have a green bar going on :-)

**Comment by sam** [comment]
It looks like we just need to add the yaml and then I can turn it on.

Hopefully be able to close out the failing tests this weekend. Except for the Rack Multipart error. Still no idea what that's from (the actual multi-part body looks fine as far as I can tell, terminated with double-CRLF's and everything).

**Comment by sam** [comment]
It appears TravisCI doesn't like the git reference in the Gemfile. Looks like I'll need to rubygem.org redis-directory before we'll be able to get a test run in.

**Comment by sam** [comment]
Well, we have our first CI run now, but it's still not getting to execute tests. It's failing with a StackLevelTooDeep: http://travis-ci.org/#!/sam/harbor/builds/787612

**Comment by sam** [comment]
This looks like the error we're hitting: https://github.com/travis-ci/travis-ci/issues/424

I tried to see if I could apply the work-around mentioned in the ticket in bfbdeca96b4edacb86ed17971de639b1943c3cc9, but no joy. Still failing. Hopefully the TravisCI and/or Bundler and/or JRuby guys figure it out soon.

**Comment by sam** [comment]
Green on JRuby! http://travis-ci.org/#!/sam/harbor/builds/823108

Basically, we have to be sure not to require Bundler more than once. So I can up with a dirty way of making sure that's the case in c4956e3d64253b4aca2a1ce4fbae9b96c1e85ffd by using: `require "bundler/setup" unless Object::const_defined("Bundler")`.

It's a bit nasty, but it works. So until TravisCI upgrades to at least JRuby 1.6.7 it'll be necessary I think since they call `bundle exec rake` and we just use `bundler/setup` so we can call `rake` without the ceremony.

**Comment by fgrehm** [comment]
Our first green bar, this is awesome :-)
